version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/logs
    ports:
      - "0.0.0.0:8000:8000"
